# Generated by Django 5.1.7 on 2025-04-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('pokemessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TradeCardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(choices=[('offer', 'Sender Offers'), ('request', 'Sender Requests')], max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_details', to='cards.card')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='pokemessages.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='cards',
            field=models.ManyToManyField(related_name='trades_involved_in', through='pokemessages.TradeCardDetail', to='cards.card'),
        ),
        migrations.DeleteModel(
            name='TradeItem',
        ),
    ]
