# Generated by Django 5.1.7 on 2025-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemessages', '0002_trade_status_alter_trade_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='trade',
            name='message',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
