# Generated by Django 5.1.7 on 2025-04-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemessages', '0003_remove_trade_accepted_alter_trade_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_read',
        ),
    ]
