# Generated by Django 5.1.5 on 2025-04-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
