# Generated by Django 5.1.7 on 2025-04-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owns',
        ),
    ]
