# Generated by Django 5.1.7 on 2025-04-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_pack_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
