# Generated by Django 5.1.7 on 2025-04-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_set_pack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
