# Generated by Django 5.1.7 on 2025-04-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_delete_pack_delete_set'),
        ('cards', '0004_pack_cost'),
    ]

    operations = [
    ]
