# Generated by Django 5.1.7 on 2025-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_merge_0004_delete_pack_delete_set_0004_pack_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#4A5568', help_text='Hex color code for UI display', max_length=7)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
